server:
  port: 8181

spring:
  application:
    name: ecommerce

  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://34.68.138.242:5432/postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui